# Generated by Django 5.2.5 on 2025-08-15 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_conteudo_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 22, 30, 2, 583272, tzinfo=datetime.timezone.utc)),
        ),
    ]
