# Generated by Django 5.2.5 on 2025-08-17 13:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Texto'),
        ),
    ]
