# Generated by Django 5.2.5 on 2025-08-17 13:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_imagem_capa_post_resumo_alter_post_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
