# Generated by Django 5.2.3 on 2025-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_conteudo_alter_post_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
